import { execFile } from 'node:child_process'
import type { IssueInfo } from '../../github/issues.js'
import { createLogger } from '../../utils/logger.js'

const log = createLogger('taicho-git')

function exec(command: string, args: string[], cwd: string): Promise<string> {
  return new Promise((resolve, reject) => {
    execFile(command, args, { cwd, maxBuffer: 10 * 1024 * 1024 }, (error, stdout, stderr) => {
      if (error) {
        reject(new Error(`${command} ${args.join(' ')} failed: ${stderr || error.message}`))
        return
      }
      resolve(stdout.trim())
    })
  })
}

function git(args: string[], cwd: string): Promise<string> {
  return exec('git', args, cwd)
}

export function slugifyTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40)
}

export function generateBranchName(issueNumber: number, title: string): string {
  const slug = slugifyTitle(title)
  return `feature/issue-${issueNumber}-${slug}`
}

/**
 * develop が存在すれば develop、なければ main を返す
 */
export async function getBaseBranch(localPath: string): Promise<string> {
  try {
    await git(['rev-parse', '--verify', 'origin/develop'], localPath)
    return 'develop'
  } catch {
    return 'main'
  }
}

/**
 * ワーキングツリーがクリーンでなければ stash する
 */
export async function ensureCleanWorkingTree(localPath: string): Promise<void> {
  const status = await git(['status', '--porcelain'], localPath)
  if (status) {
    log.info('Working tree is dirty, stashing changes')
    await git(['stash', 'push', '-m', 'taicho-auto-stash'], localPath)
  }
}

/**
 * リモートを fetch し、ベースブランチをチェックアウトして最新にする
 */
export async function fetchAndCheckoutBase(localPath: string, baseBranch: string): Promise<void> {
  await git(['fetch', 'origin'], localPath)
  await git(['checkout', baseBranch], localPath)
  await git(['pull', 'origin', baseBranch], localPath)
}

/**
 * フィーチャーブランチを作成してチェックアウトする
 */
export async function createFeatureBranch(
  localPath: string,
  branchName: string,
  baseBranch: string,
): Promise<void> {
  await fetchAndCheckoutBase(localPath, baseBranch)
  await git(['checkout', '-b', branchName], localPath)
  log.info(`Created branch: ${branchName}`)
}

/**
 * ベースブランチ以降に新しいコミットがあるか確認する
 */
export async function hasNewCommits(localPath: string, baseBranch: string): Promise<boolean> {
  const output = await git(['log', `${baseBranch}..HEAD`, '--oneline'], localPath)
  return output.length > 0
}

/**
 * ブランチをリモートに push する
 */
export async function pushBranch(localPath: string, branchName: string): Promise<void> {
  await git(['push', '-u', 'origin', branchName], localPath)
  log.info(`Pushed branch: ${branchName}`)
}

/**
 * Draft PR を作成し、PR URL を返す
 */
export async function createDraftPR(
  repo: string,
  branchName: string,
  baseBranch: string,
  issue: IssueInfo,
): Promise<string> {
  const title = `feat: ${issue.title} (#${issue.number})`
  const body = [
    `## Summary`,
    ``,
    `Closes #${issue.number}`,
    ``,
    `タイチョーによる自動実装。`,
    ``,
    `## Original Issue`,
    ``,
    `**${issue.title}**`,
    ``,
    issue.body ?? '',
    ``,
    `---`,
    `Generated by Taicho Agent`,
  ].join('\n')

  const url = await exec(
    'gh',
    [
      'pr', 'create',
      '--repo', repo,
      '--base', baseBranch,
      '--head', branchName,
      '--title', title,
      '--body', body,
      '--draft',
    ],
    process.cwd(),
  )

  log.info(`Created Draft PR: ${url}`)
  return url
}

/**
 * 失敗時のブランチクリーンアップ
 */
export async function cleanupBranch(
  localPath: string,
  baseBranch: string,
  branchName: string,
): Promise<void> {
  try {
    await git(['checkout', baseBranch], localPath)
    await git(['branch', '-D', branchName], localPath)
    log.info(`Cleaned up branch: ${branchName}`)
  } catch (err) {
    log.warn(`Branch cleanup failed: ${(err as Error).message}`)
  }
}

/**
 * ブランチをベースにハードリセットする（リトライ時に使用）
 */
export async function resetToBase(localPath: string, baseBranch: string): Promise<void> {
  await git(['reset', '--hard', baseBranch], localPath)
  await git(['clean', '-fd'], localPath)
  log.info(`Reset to ${baseBranch}`)
}
